services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: db2
      POSTGRES_PASSWORD: db2
      POSTGRES_DB: db2
    volumes:
      - url-shortener_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://db2:db2@db:5432/db2

volumes:
  url-shortener_pgdata:
