"""init

Revision ID: e42697b14fba
Revises: 
Create Date: 2025-06-12 02:19:22.299004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e42697b14fba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('short_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_url_original_url'), 'url', ['original_url'], unique=True)
    op.create_index(op.f('ix_url_short_code'), 'url', ['short_code'], unique=True)
    op.create_table('url_visit',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('url_id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_url_visit_url_id'), 'url_visit', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_visit_url_id'), table_name='url_visit')
    op.drop_table('url_visit')
    op.drop_index(op.f('ix_url_short_code'), table_name='url')
    op.drop_index(op.f('ix_url_original_url'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
